"""Create enhanced trading database schema

Revision ID: 4b6b797adaeb
Revises: 
Create Date: 2025-09-25 21:08:34.779439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6b797adaeb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('account_hash', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_hash'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index('idx_accounts_hash', 'accounts', ['account_hash'], unique=False)
    op.create_index('idx_accounts_type', 'accounts', ['account_type'], unique=False)
    op.create_table('options_expirations',
    sa.Column('expiration_id', sa.BigInteger(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=10), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('days_to_expiration', sa.Integer(), nullable=True),
    sa.Column('expiration_type', sa.String(length=1), nullable=False),
    sa.Column('is_standard', sa.Boolean(), nullable=True),
    sa.Column('is_leap', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("expiration_type IN ('W', 'S', 'Q', 'M')"),
    sa.PrimaryKeyConstraint('expiration_id'),
    sa.UniqueConstraint('underlying_symbol', 'expiration_date')
    )
    op.create_index('idx_exp_symbol_date', 'options_expirations', ['underlying_symbol', 'expiration_date'], unique=False)
    op.create_index('idx_exp_type_dte', 'options_expirations', ['expiration_type', 'days_to_expiration'], unique=False)
    op.create_table('price_data',
    sa.Column('price_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('datetime_ms', sa.BigInteger(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('previous_close_date_ms', sa.BigInteger(), nullable=True),
    sa.Column('is_empty', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=True),
    sa.Column('frequency_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('symbol', 'datetime_ms', 'frequency_type')
    )
    op.create_index('idx_price_datetime', 'price_data', ['datetime_utc'], unique=False)
    op.create_index('idx_price_symbol_datetime', 'price_data', ['symbol', 'datetime_utc'], unique=False)
    op.create_index('idx_price_volume', 'price_data', ['volume'], unique=False)
    op.create_table('symbols',
    sa.Column('symbol_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol_id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('idx_symbols_symbol', 'symbols', ['symbol'], unique=False)
    op.create_index('idx_symbols_type', 'symbols', ['asset_type'], unique=False)
    op.create_table('options_chains',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=10), nullable=False),
    sa.Column('expiration_id', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=True),
    sa.Column('underlying_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('underlying_bid', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('underlying_ask', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('underlying_last', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('underlying_volume', sa.BigInteger(), nullable=True),
    sa.Column('underlying_change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('underlying_percent_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('implied_volatility', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_delayed', sa.Boolean(), nullable=True),
    sa.Column('is_index', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expiration_id'], ['options_expirations.expiration_id'], ),
    sa.PrimaryKeyConstraint('chain_id'),
    sa.UniqueConstraint('underlying_symbol', 'expiration_id', 'snapshot_datetime')
    )
    op.create_index('idx_chains_expiration', 'options_chains', ['expiration_id'], unique=False)
    op.create_index('idx_chains_symbol_snapshot', 'options_chains', ['underlying_symbol', 'snapshot_datetime'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('schwab_order_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('session', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('order_strategy_type', sa.String(length=20), nullable=True),
    sa.Column('complex_order_strategy_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('remaining_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('activation_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stop_price_offset', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_link_basis', sa.String(length=20), nullable=True),
    sa.Column('price_link_type', sa.String(length=20), nullable=True),
    sa.Column('stop_price_link_basis', sa.String(length=20), nullable=True),
    sa.Column('stop_price_link_type', sa.String(length=20), nullable=True),
    sa.Column('requested_destination', sa.String(length=20), nullable=True),
    sa.Column('destination_link_name', sa.String(length=50), nullable=True),
    sa.Column('special_instruction', sa.String(length=50), nullable=True),
    sa.Column('tax_lot_method', sa.String(length=20), nullable=True),
    sa.Column('stop_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.Column('entered_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelable', sa.Boolean(), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('schwab_order_id')
    )
    op.create_index('idx_orders_account_status', 'orders', ['account_id', 'status'], unique=False)
    op.create_index('idx_orders_entered_time', 'orders', ['entered_time'], unique=False)
    op.create_index('idx_orders_schwab_id', 'orders', ['schwab_order_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_table('options_contracts',
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=True),
    sa.Column('option_symbol', sa.String(length=50), nullable=False),
    sa.Column('put_call', sa.String(length=4), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('days_to_expiration', sa.Integer(), nullable=True),
    sa.Column('bid_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ask_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bid_size', sa.Integer(), nullable=True),
    sa.Column('ask_size', sa.Integer(), nullable=True),
    sa.Column('last_size', sa.Integer(), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('trade_date', sa.BigInteger(), nullable=True),
    sa.Column('quote_time', sa.BigInteger(), nullable=True),
    sa.Column('trade_time', sa.BigInteger(), nullable=True),
    sa.Column('net_change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('percent_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mark_change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mark_percent_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('delta', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('rho', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('time_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('intrinsic_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('theoretical_option_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('theoretical_volatility', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_in_the_money', sa.Boolean(), nullable=True),
    sa.Column('is_mini', sa.Boolean(), nullable=True),
    sa.Column('is_non_standard', sa.Boolean(), nullable=True),
    sa.Column('is_index_option', sa.Boolean(), nullable=True),
    sa.Column('is_penny_pilot', sa.Boolean(), nullable=True),
    sa.Column('expiration_type', sa.String(length=1), nullable=True),
    sa.Column('last_trading_day', sa.BigInteger(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('settlement_type', sa.String(length=1), nullable=True),
    sa.Column('deliverable_note', sa.Text(), nullable=True),
    sa.Column('option_root', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("expiration_type IN ('M', 'W', 'Q')"),
    sa.CheckConstraint("put_call IN ('PUT', 'CALL')"),
    sa.CheckConstraint("settlement_type IN ('A', 'P')"),
    sa.ForeignKeyConstraint(['chain_id'], ['options_chains.chain_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index('idx_contracts_chain_type_strike', 'options_contracts', ['chain_id', 'put_call', 'strike_price'], unique=False)
    op.create_index('idx_contracts_oi', 'options_contracts', ['open_interest'], unique=False)
    op.create_index('idx_contracts_symbol_exp', 'options_contracts', ['option_symbol', 'expiration_date'], unique=False)
    op.create_index('idx_contracts_underlying_exp_strike', 'options_contracts', ['chain_id', 'expiration_date', 'strike_price'], unique=False)
    op.create_index('idx_contracts_volume', 'options_contracts', ['total_volume'], unique=False)
    op.create_table('order_activities',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_type', sa.String(length=20), nullable=True),
    sa.Column('execution_type', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('order_remaining_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index('idx_activities_order', 'order_activities', ['order_id'], unique=False)
    op.create_index('idx_activities_type', 'order_activities', ['activity_type'], unique=False)
    op.create_table('order_legs',
    sa.Column('leg_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('schwab_leg_id', sa.Integer(), nullable=True),
    sa.Column('order_leg_type', sa.String(length=20), nullable=True),
    sa.Column('instruction', sa.String(length=20), nullable=True),
    sa.Column('position_effect', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('quantity_type', sa.String(length=20), nullable=True),
    sa.Column('instrument_cusip', sa.String(length=20), nullable=True),
    sa.Column('instrument_symbol', sa.String(length=50), nullable=True),
    sa.Column('instrument_description', sa.Text(), nullable=True),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('instrument_type', sa.String(length=50), nullable=True),
    sa.Column('instrument_net_change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('to_symbol', sa.String(length=50), nullable=True),
    sa.Column('div_cap_gains', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leg_id')
    )
    op.create_index('idx_legs_instruction', 'order_legs', ['instruction'], unique=False)
    op.create_index('idx_legs_order', 'order_legs', ['order_id'], unique=False)
    op.create_index('idx_legs_symbol', 'order_legs', ['instrument_symbol'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('schwab_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sub_account', sa.String(length=20), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('user_cd_domain_id', sa.String(length=50), nullable=True),
    sa.Column('user_login', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_system_name', sa.String(length=100), nullable=True),
    sa.Column('user_first_name', sa.String(length=100), nullable=True),
    sa.Column('user_last_name', sa.String(length=100), nullable=True),
    sa.Column('broker_rep_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('schwab_activity_id')
    )
    op.create_index('idx_transactions_account_time', 'transactions', ['account_id', 'transaction_time'], unique=False)
    op.create_index('idx_transactions_order_id', 'transactions', ['order_id'], unique=False)
    op.create_index('idx_transactions_schwab_id', 'transactions', ['schwab_activity_id'], unique=False)
    op.create_index('idx_transactions_trade_date', 'transactions', ['trade_date'], unique=False)
    op.create_index('idx_transactions_type_status', 'transactions', ['transaction_type', 'status'], unique=False)
    op.create_table('execution_legs',
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=True),
    sa.Column('leg_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('mismarked_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['order_activities.activity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leg_id'], ['order_legs.leg_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('idx_executions_activity', 'execution_legs', ['activity_id'], unique=False)
    op.create_index('idx_executions_leg', 'execution_legs', ['leg_id'], unique=False)
    op.create_index('idx_executions_time', 'execution_legs', ['execution_time'], unique=False)
    op.create_table('option_deliverables',
    sa.Column('deliverable_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=True),
    sa.Column('deliverable_units', sa.String(length=50), nullable=True),
    sa.Column('currency_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['options_contracts.contract_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deliverable_id')
    )
    op.create_index('idx_deliverables_contract', 'option_deliverables', ['contract_id'], unique=False)
    op.create_table('transaction_items',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('cost', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('position_effect', sa.String(length=20), nullable=True),
    sa.Column('fee_type', sa.String(length=20), nullable=True),
    sa.Column('instrument_cusip', sa.String(length=20), nullable=True),
    sa.Column('instrument_symbol', sa.String(length=50), nullable=True),
    sa.Column('instrument_description', sa.Text(), nullable=True),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('instrument_type', sa.String(length=50), nullable=True),
    sa.Column('instrument_net_change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_items_fee_type', 'transaction_items', ['fee_type'], unique=False)
    op.create_index('idx_items_position_effect', 'transaction_items', ['position_effect'], unique=False)
    op.create_index('idx_items_symbol', 'transaction_items', ['instrument_symbol'], unique=False)
    op.create_index('idx_items_transaction', 'transaction_items', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_items_transaction', table_name='transaction_items')
    op.drop_index('idx_items_symbol', table_name='transaction_items')
    op.drop_index('idx_items_position_effect', table_name='transaction_items')
    op.drop_index('idx_items_fee_type', table_name='transaction_items')
    op.drop_table('transaction_items')
    op.drop_index('idx_deliverables_contract', table_name='option_deliverables')
    op.drop_table('option_deliverables')
    op.drop_index('idx_executions_time', table_name='execution_legs')
    op.drop_index('idx_executions_leg', table_name='execution_legs')
    op.drop_index('idx_executions_activity', table_name='execution_legs')
    op.drop_table('execution_legs')
    op.drop_index('idx_transactions_type_status', table_name='transactions')
    op.drop_index('idx_transactions_trade_date', table_name='transactions')
    op.drop_index('idx_transactions_schwab_id', table_name='transactions')
    op.drop_index('idx_transactions_order_id', table_name='transactions')
    op.drop_index('idx_transactions_account_time', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_legs_symbol', table_name='order_legs')
    op.drop_index('idx_legs_order', table_name='order_legs')
    op.drop_index('idx_legs_instruction', table_name='order_legs')
    op.drop_table('order_legs')
    op.drop_index('idx_activities_type', table_name='order_activities')
    op.drop_index('idx_activities_order', table_name='order_activities')
    op.drop_table('order_activities')
    op.drop_index('idx_contracts_volume', table_name='options_contracts')
    op.drop_index('idx_contracts_underlying_exp_strike', table_name='options_contracts')
    op.drop_index('idx_contracts_symbol_exp', table_name='options_contracts')
    op.drop_index('idx_contracts_oi', table_name='options_contracts')
    op.drop_index('idx_contracts_chain_type_strike', table_name='options_contracts')
    op.drop_table('options_contracts')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_schwab_id', table_name='orders')
    op.drop_index('idx_orders_entered_time', table_name='orders')
    op.drop_index('idx_orders_account_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_chains_symbol_snapshot', table_name='options_chains')
    op.drop_index('idx_chains_expiration', table_name='options_chains')
    op.drop_table('options_chains')
    op.drop_index('idx_symbols_type', table_name='symbols')
    op.drop_index('idx_symbols_symbol', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('idx_price_volume', table_name='price_data')
    op.drop_index('idx_price_symbol_datetime', table_name='price_data')
    op.drop_index('idx_price_datetime', table_name='price_data')
    op.drop_table('price_data')
    op.drop_index('idx_exp_type_dte', table_name='options_expirations')
    op.drop_index('idx_exp_symbol_date', table_name='options_expirations')
    op.drop_table('options_expirations')
    op.drop_index('idx_accounts_type', table_name='accounts')
    op.drop_index('idx_accounts_hash', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
